apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pointlesswaste-chess-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: portfolio-api-service
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - chess.pointlesswaste.com
    secretName: chess-tls-cert
  rules:
  - host: chess.pointlesswaste.com
    http:
      paths:
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: portfolio-api-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-public
            port:
              number: 80
